In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/CunyLaguardiaDataAnalytics/datasets/master/mtcars.csv')

In [ ]:
df.head()

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [ ]:
df.shape

(32, 12)

In [ ]:
df.columns

Index(['Unnamed: 0', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

In [ ]:
df = df.rename(columns={'Unnamed: 0': 'car_model'})

In [ ]:
print(df.columns)

Index(['car_model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

In [3]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/CunyLaguardiaDataAnalytics/datasets/master/mtcars.csv')

In [4]:
df_subset = df[['mpg', 'hp', 'wt', 'cyl']]

In [6]:
df = df.rename(columns={'cylinders': 'cyl'})

In [7]:
df_subset['mpg'].mean()

np.float64(20.090625000000003)

In [8]:
df_8cyl = df[df['cyl'] == 8]

In [9]:

df_8cyl[['mpg', 'hp', 'wt']].describe()

             mpg          hp         wt
count  14.000000   14.000000  14.000000
mean   15.100000  209.214286   3.999214
std     2.560048   50.976886   0.759405
min    10.400000  150.000000   3.170000
25%    14.400000  176.250000   3.532500
50%    15.200000  192.500000   3.755000
75%    16.250000  241.250000   4.013750
max    19.200000  335.000000   5.424000